Repository jblxo/bombak, pull requests merged in 2019-05, with the labels that each got.

#11 Add Basic Drawing And Threads
  Bombak/Bomb.cs
  Bombak/Entity.cs
  Bombak/Form1.Designer.cs
  Bombak/Form1.cs
  Bombak/Runner.cs
  Bombak/SetField.Designer.cs
  Bombak/SetField.cs
  Bombak/Settings.cs
Labels: enhancement

#13 Add Randomly Running Runners
  Bombak/Entity.cs
  Bombak/EntityFactory.cs
  Bombak/Form1.cs
  Bombak/Runner.cs
  Bombak/Settings.cs
Labels: enhancement

#17 Fix Drawing Of Runners With Different Sizes of Field
  Bombak/MainForm.cs
Labels: fix

#22 Zajda&ondra
  Bombak/Bomb.cs
  Bombak/Canvas.Designer.cs
  Bombak/Canvas.cs
  Bombak/Entity.cs
  Bombak/EntityFactory.cs
  Bombak/MainForm.Designer.cs
  Bombak/MainForm.cs
  Bombak/Runner.cs
Labels: enhancement

#23 Add IM button and Bomb Detonation
  Bombak/Bomb.cs
  Bombak/Canvas.cs
  Bombak/EntityFactory.cs
  Bombak/MainForm.Designer.cs
  Bombak/MainForm.cs
Labels: enhancement

#24 Speed slider, thanos button bug, bomb fleeing fix
  Bombak/Bomb.cs
  Bombak/Canvas.cs
  Bombak/EntityFactory.cs
  Bombak/MainForm.Designer.cs
  Bombak/MainForm.cs
  Bombak/Runner.cs
  Bombak/Settings.cs
Labels: bug, enhancement
